config/routes.rb
Rails.application.routes.draw do
  
  root to: "main#index"

  get "sign_up", to: "register#new"
  post "sign_up", to: "register#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "giftcard", to: "giftcard#order"

  get "new_order", to: "giftcard#neworder"
  post "new_order", to: "giftcard#create"
  get "order_history", to: "giftcard#orderhistory"

  get "admin", to: "adminpage#showalltable"
  get "order/:id/edit", to: "adminpage#edit"
  post "order/:id/edit", to: "adminpage#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/giftcoupon.rb
class Giftcoupon < ApplicationRecord
  belongs_to :user_x
end

app/models/user_x.rb
class UserX < ApplicationRecord
    has_many :giftcoupons

    has_secure_password

    validates :username, presence: true
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/adminpage_controller.rb
class AdminpageController < ApplicationController
    def showalltable
        if session[:user_id] && Current.user.role == true
            @user = UserX.find_by(id: session[:user_id])
        end
        @giftcoupon = Giftcoupon.all
    end

    def edit
        @giftcoupon = Giftcoupon.find_by(id: params[:id])
    end

    def update
        @giftcoupon = Giftcoupon.find_by(id: params[:id])
        @giftcoupon.update(status: params[:giftcoupon][:status])
        redirect_to admin_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = UserX.find_by(id: session[:user_id])
        end
    end
end

app/controllers/giftcard_controller.rb
class GiftcardController < ApplicationController
    def neworder
        @giftcoupon = Giftcoupon.new(order_date: Date.current)
    end

    def create
        @giftcoupon = Giftcoupon.new(order_params)
        @giftcoupon.user_x_id = session[:user_id]
        @temp_date = DateTime.now.strftime "%d/%m/%y"
        @giftcoupon.order_date = @temp_date
        @giftcoupon.status = "OUT FOR DELIVERY"
        if @giftcoupon.save
            redirect_to order_history_path
        else
            render :neworder
        end
    end

    def order 
        if session[:user_id]
            @user = UserX.find_by(id: session[:user_id])
        end
    end

    def orderhistory
        @giftcoupon = Giftcoupon.all
    end

    def update
        @giftcoupon = Giftcoupon.find_by(id: params[:id])
        @giftcoupon.update(status: params[:giftcoupon][:status])
        redirect_to admin_path
    end

    private

        def order_params
            params.require(:giftcoupon).permit(:first_name, :last_name, :gift_card_value, :total_amount, :mobile_no, :address)
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
            @user = UserX.find_by(id: session[:user_id])
        end
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def new
    @user = UserX.new
    end

    def create
        @user = UserX.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to giftcard_path, notice: "Succesfully created account"
        else
            render :new
        end
    end

    private

        def user_params
            params.require(:user_x).permit(:username, :email, :password, :password_confirmation)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = UserX.new
    end

    def create
        user = UserX.find_by(username: params[:username])
        
        if  user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to giftcard_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged Out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adminpage/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Gift Card', root_path, class:"navbar-brand"%>>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class=" navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item ">
            <%= link_to 'Order History', admin_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
            <%= link_to 'Monthly Report', admin_path, class: 'nav-link' %>
        </li>
      </ul>
      <%# <ul class="nav navbar-nav navbar-right px-4"> %>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">
        <% if Current.user %>
            <li class="nav-item">
               <span class="nav-link">Logged in as: <%= Current.user.email%></span>
            </li>
            <li class = "nav-item">
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
            </li>
        <% else %>
        <li class="nav-item">
            <%= link_to 'Register', register_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Login', sign_in_path, class: 'nav-link' %>
        </li>
        <%end%>
        <%# <li class="nav-item">
            <%= button_to 'Logout', logout_path, method: :delete, class: 'nav-button btn btn-danger' %>
        <%# </li> %>
      </ul>
    </div>
  </div>
</nav>

app/views/adminpage/edit.html.erb
<div class="container card col-sm-4 my-4 p-4">
    <h3>Update Order</h3>
    <%= form_for :giftcoupon do |f| %>
        <div class="mb-3">
            
            <label class="mb-2">Delivery Status</label>
            <%= f.text_field :status, autofocus: true, class: "form-control" %>
        </div>
        <div class="mb-3 d-flex justify-content-center">
            <%= f.submit "Update Order", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/adminpage/showalltable.html.erb
<%= render  'navbar'%>
<div class="container">
    <h2 class="d-flex justify-content-center align-items-center m-4">Order History</h2>
    <table class="table table-striped table-bordered table-hover  ">
        <thead class="thead-dark">
            <tr>
                <th>Order Id</th>
                <th>Recipient Name</th>
                <th>Ordered Date</th>
                <th>Gift card Value</th>
                <th>Commission (5%)</th>
                <th>Delivery Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% Giftcoupon.all.each do |giftcoupon|%>
                    <tr>
                        <td><%=giftcoupon.id%></td>
                        <td><%=giftcoupon.first_name + " " + giftcoupon.last_name%></td>
                        <td><%=giftcoupon.order_date%></td>
                        <td><%=giftcoupon.gift_card_value%></td>
                        <td><%=giftcoupon.total_amount%></td>
                        <td><b><%=giftcoupon.status%></b></td>
                        <td><a href="order/<%=giftcoupon.id%>/edit"class="btn btn-success">Mark Delivered</a></td>
                    </tr>
                
            <%end%>
        </tbody>

    </table>

</div>

app/views/giftcard/_navbar.html.erb
<% if Current.user.role == false%>
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to 'Gift Card', giftcard_path, class:"navbar-brand"%>>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'New Orders', new_order_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to 'Order History', order_history_path, class: 'nav-link' %>
        </li>
    </ul>
    <ul class = "navbar-nav ns-auto mb-2 mb-lg-0 ">
      <% if Current.user %>
        <li class = "nav-items">
          <span class = "nav-link"><%= Current.user.email %></span>
        </li>
        <li class = "nav-tems">
          <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-danger" %>
        </li>
      <%end%>
    </ul>
    </div>
  </div>
</nav>
<%else%>
<%= render "adminpage/navbar"%>
<%end%>

app/views/giftcard/neworder.html.erb
<%= render "navbar" %>

<div class ="container rounded-5 card col-sm-6 my-4 py-2">
<%= form_with model: @giftcoupon, url: new_order_path do |form| %>
  <h2 class="text-center p-4">Create New Order</h2>
  <div class="row">
    <div class="col-sm-6 my-2">
      <label>Date: </label>
      <%= Time.now.strftime("%F")%>
    </div>
  </div>
  <div class="row">
    <div class="mb-3 col-sm-6 ">
        <label>Recepient First Name</label>
        <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
    </div>

    <div class="mb-3 col-sm-6 ">
        <label>Recepient Last Name</label>
        <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
    </div>
  </div>
  <div class="row">
    <div class="mb-3 col-sm-6 ">
        <label>Gift Card Value(INR)</label>
        <%= form.number_field :gift_card_value, class: "form-control", placeholder: "Gift Card Value", id: :val, onchange: "fun()" %>
    </div>

    <div class="mb-3 col-sm-6 ">
        <label>Amount Payable(5% Commision Rate)</label> 
        <%= form.number_field :total_amount, step: :any, class: "form-control", placeholder: "Amount Payable", id: :res %>
    </div>
  </div>
  
  <div class="row">
    <div class="mb-3 col-sm-6 ">
        <%= form.label :address %> 
        <%= form.text_field :address, class: "form-control", placeholder: "Recepient Address" %>
    </div>

    <div class="mb-3 col-sm-6 ">
        <label>Racepient Mobile Number</label>
        <%= form.text_field :mobile_no, class: "form-control", placeholder: "Recepient Mobile Number" %>
    </div>
  </div>
  <div class = "mb-3 d-flex align-item-center justify-content-center">
    <%= form.submit "Place Order", class: "btn btn-success" %>
  </div>
<% end %>
</div>
<script>
function fun() {
  num = document.getElementById("val").value;
  num= parseInt(num);
  result = num*(0.05);
  document.getElementById("res").value=result;
}
</script>

app/views/giftcard/order.html.erb
<%= render "navbar" %>

<h1 class="text-center">GiftCard</h1>
<div class = "mb-3 d-flex align-item-center justify-content-center" >
    <% if Current.user %>
    Logged in as: <%= Current.user.email %>
        <%= button_to "Logout", logout_path, class: "btn btn-danger",  method: :delete %>
    <% end %>
</div>

app/views/giftcard/orderhistory.html.erb
<%= render "navbar" %>

<div class ="container rounded-3 card col-sm-12 my-2 py-2">
    <h2 class="text-center">Order History</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
            <th scope="col">Order Id</th>
            <th scope="col">Recipient Name</th>
            <th scope="col">Ordered Date</th>
            <th scope="col">Gift Card Value</th>
            <th scope="col">Commision (5%)</th>
            <th scope="col">Delivery Status</th>
            </tr>
        </thead>
        <tbody>
        <% Giftcoupon.all.each do |order| %>
            <% if order.user_x == Current.user %>
                <tr>
                <th scope="row"><%= order.id %></th>
                <td><%= order.first_name+" "+order.last_name%></td>
                <td><%= order.created_at.strftime('%F') %></td>
                <td><%= order.gift_card_value %></td>
                <td><%= order.total_amount %></td>
                <td><%= order.status %></td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giftcard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
      <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <% if Current.user%>
      <%= link_to 'Gift Card', giftcard_path, class:"navbar-brand"%>
    <%else%>
      <%= link_to 'Gift Card', root_path, class:"navbar-brand"%>
    <%end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
    </ul>
      <ul class="nav navbar-nav navbar-right px-4">
        <li class="nav-item">
           <%= link_to 'Log In', sign_in_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
           <%= link_to 'Register', sign_up_path, class: 'nav-link' %>
        </li>
    </ul>
   
    </div>
  </div>
</nav>

app/views/main/index.html.erb
    <html>
    <head>
        <style>
            body {
                background-image: url(https://i.pinimg.com/originals/5c/94/a5/5c94a5c141f42a7d26ce3fa5c6d734ad.gif);
                height: auto; 
                background-repeat: no-repeat; 
                background-size: cover;
                font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
                font-size: 14px;
                line-height: 1.42857143;
                color: #333;
                background-color: #fff;
            }
            h1{
                font-size: 40px;
                font-weight: bold;
                color: #fff;
                text-align: center;
                margin-top: 50px;
                text-align: center;
            }
        </style>
    </head>
        <body>
            <%= render "navbar" %>  
            <div class = "mb-4 text-align-center" >
                <h1>Welcome to Giftcard Management System</h1>
                <% if Current.user %>
                    Logged in as: <%= Current.user.email %>
                    <%= button_to "Logout", logout_path, class: "btn btn-danger",  method: :delete %>
                <% end %>
            </div>
        </body>
    </html>

app/views/register/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to 'Gift Card', root_path, class:"navbar-brand"%>>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
    </ul>
      <ul class="nav navbar-nav navbar-right px-4">
        <li class="nav-item">
           <%= link_to 'Log In', sign_in_path, class: 'nav-link' %>
        </li>
    </ul>
    </div>
  </div>
</nav>

app/views/register/new.html.erb
<%= render "navbar" %>

    <div class ="container rounded-5 card col-sm-4 my-4 py-2">
    <%= form_with model: @user, url: sign_up_path do |form| %>
        <% if @user.errors.any? %>
            <div class = "alert alert-danger">
                <% @user.errors.full_messages.each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
        <% end %>
        <h2 class="text-center py-2">Register</h2>
        <div class = "mb-3">
            <%= form.label :username %> 
            <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
        </div>
        
        <div class = "mb-3">
            <%= form.label :email %> 
            <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>
        
        <div class = "mb-3">
            <%= form.label :password %> 
            <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>

        <div class = "mb-3" >
            <%= form.label :password_confirmation %> 
            <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
        </div>

        <div class = "mb-3 text-center">
            <%= form.submit "Register", class: "btn btn-success" %>
        </div>

    <% end %>
    </div>